---

- name: Installing and configuring zabbix-agent
  hosts: all
  tasks:

    - stat:
        path: "/etc/yum.repos.d/zabbix.repo"
      register: result

    - name: "Add zabbix repository CentOS 7"
      command: "rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
        - result.stat.exists == false

    - name: "Add zabbix repository CentOS 7"
      command: "rpm -Uvh http://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8"
        - result.stat.exists == false

    - name: "Add zabbix repository CentOS 6"
      command: "rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "6"
        - result.stat.exists == false
