---
- name: "Add repo if does not exist"
  stat:
    path: "/etc/yum.repos.d/zabbix.repo"
  register: zabbix_repo

- name: "Add zabbix repository CentOS 7"
  command: "rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
    - zabbix_repo.stat.exists == false

- name: "Add zabbix repository CentOS 8"
  command: "rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm"
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
    - zabbix_repo.stat.exists == false

- name: "Install zabbix-agent"
  yum:
    name: zabbix-agent
    state: latest

- name: "Create config Zabbix Agent config file"
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644

- name: "Start and enable zabbix-agent.service"
  service:
    name: zabbix-agent
    state: started
    enabled: yes
