---

- name: Installing and configuring zabbix-agent
  hosts: all
  tasks:

    - stat:
        path: "/etc/yum.repos.d/zabbix.repo"
      register: zabbix_repo

    - name: "Add zabbix repository CentOS 7"
      command: "rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
        - zabbix_repo.stat.exists == false

    - name: "Add zabbix repository CentOS 8"
      command: "rpm -Uvh http://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8"
        - zabbix_repo.stat.exists == false

    - name: "Add zabbix repository CentOS 6"
      command: "rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm"
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "6"
        - zabbix_repo.stat.exists == false

    - name: "Install zabbix-agent"
      yum:
        name: zabbix-agent
        state: latest

    - name: "Adjust zabbix-agent config file"
      template:
        src: zabbix_agentd.conf.j2
        dest: "/etc/zabbix/zabbix_agentd.conf"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart zabbix-agent

    - name: "Start and enable zabbix-agent.service"
      service:
        name: zabbix-agent
        state: started
        enabled: yes
